#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Aliases
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc" 

PS1='[\u@\h \W]\$ '

# Most important thing here
fastfetch
